artifact_location: file:///home/work/grad_school/wooshikwon/weighted_mtp/mlruns/0
creation_time: 1764051598698
experiment_id: '0'
last_update_time: 1764051598698
lifecycle_stage: active
name: Default
