artifact_location: file:///home/work/grad_school/wooshikwon/weighted_mtp/mlruns/869427667672898361
creation_time: 1764051598704
experiment_id: '869427667672898361'
last_update_time: 1764051598704
lifecycle_stage: active
name: weighted-mtp/production
